import type { AnswerChoice, PracticeQuestion } from './types'

const fuChoices: AnswerChoice[] = [
  { key: '20', label: '20符' },
  { key: '25', label: '25符' },
  { key: '30', label: '30符' },
  { key: '40', label: '40符' },
  { key: '50', label: '50符' },
  { key: '60', label: '60符' },
  { key: '70', label: '70符' },
  { key: 'not-needed', label: '符は不要', helper: '満貫以上または役満' },
]

const han = (values: number[], extra: AnswerChoice[] = []): AnswerChoice[] => [
  ...values.map((value) => ({ key: String(value), label: `${value}翻` })),
  ...extra,
]

const yakuCatalog: Record<string, AnswerChoice> = {
  riichi: { key: 'riichi', label: '立直' },
  'double-riichi': { key: 'double-riichi', label: 'ダブル立直' },
  ippatsu: { key: 'ippatsu', label: '一発' },
  'menzen-tsumo': { key: 'menzen-tsumo', label: '門前清自摸和' },
  pinfu: { key: 'pinfu', label: '平和' },
  tanyao: { key: 'tanyao', label: '断么九' },
  iipeiko: { key: 'iipeiko', label: '一盃口' },
  chiitoitsu: { key: 'chiitoitsu', label: '七対子' },
  'yakuhai-haku': { key: 'yakuhai-haku', label: '白' },
  'yakuhai-hatsu': { key: 'yakuhai-hatsu', label: '發' },
  'yakuhai-chun': { key: 'yakuhai-chun', label: '中' },
  toitoi: { key: 'toitoi', label: '対々和' },
  sananko: { key: 'sananko', label: '三暗刻' },
  sanshoku: { key: 'sanshoku', label: '三色同順' },
  honitsu: { key: 'honitsu', label: '混一色' },
  chanta: { key: 'chanta', label: '全帯么九' },
  kokushi: { key: 'kokushi', label: '国士無双' },
}

const yaku = (keys: string[]): AnswerChoice[] =>
  keys.map((key) => yakuCatalog[key])

export const practiceQuestions: PracticeQuestion[] = [
  {
    id: 'q-pinfu-ron-30-4-child',
    title: '平和ロンは30符で止める',
    difficulty: 'starter',
    prompt: '子のロン和了。成立役・翻・符・支払いを選んでください。',
    context: {
      seatWind: '南',
      roundWind: '東',
      dealer: false,
      method: 'ron',
      riichi: '立直',
      conditions: ['門前', 'ロン和了'],
      doraIndicators: ['1m'],
      ruleNotes: ['Mリーグ準拠', '0本場・供託なし'],
    },
    hand: ['2m', '3m', '4m', '3m', '4m', '5m', '4p', '5p', '6p', '5p', '5p', '6s', '7s'],
    winningTile: '8s',
    melds: [],
    options: {
      yaku: yaku(['riichi', 'menzen-tsumo', 'pinfu', 'tanyao', 'iipeiko', 'sanshoku']),
      han: han([3, 4, 5, 6]),
      fu: fuChoices,
      payment: [
        { key: 'child-ron-3900', label: '3900点' },
        { key: 'child-ron-5200', label: '5200点' },
        { key: 'child-ron-7700', label: '7700点' },
        { key: 'child-ron-8000', label: '8000点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['riichi', 'tanyao', 'pinfu'],
        hanKey: '4',
        hanLabel: '4翻',
        fuKey: '30',
        fuLabel: '30符',
        paymentKey: 'child-ron-7700',
        paymentLabel: '7700点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['riichi', 'tanyao', 'pinfu'],
      hanKey: '4',
      hanLabel: '4翻',
      fuKey: '30',
      fuLabel: '30符',
      paymentKey: 'child-ron-7700',
      paymentLabel: '7700点',
    },
    fuRequired: true,
    yaku: [
      { label: '立直', value: '1翻' },
      { label: '断么九', value: '1翻' },
      { label: '平和', value: '1翻' },
      { label: 'ドラ', value: '1翻', note: 'ドラ表示牌一萬なので二萬がドラ' },
    ],
    fu: [
      { label: '副底', value: '20符' },
      { label: '門前ロン', value: '10符' },
      { label: '平和形', value: '0符' },
    ],
    explanation:
      '平和ロンはツモ符がなくても、門前ロンの10符が付いて30符になります。4翻30符の子ロンは7700点です。',
    guideAnchors: ['flow', 'fu', 'table'],
  },
  {
    id: 'q-pinfu-tsumo-20-3-dealer',
    title: '親の平和ツモは20符',
    difficulty: 'starter',
    prompt: '親のツモ和了。成立役・翻・符・支払いを選んでください。',
    context: {
      seatWind: '東',
      roundWind: '東',
      dealer: true,
      method: 'tsumo',
      conditions: ['門前', 'ツモ和了'],
      doraIndicators: ['3p'],
      ruleNotes: ['Mリーグ準拠', '0本場・供託なし'],
    },
    hand: ['2m', '3m', '4m', '3p', '4p', '5p', '4s', '5s', '6s', '6p', '7p', '8p', '2z'],
    winningTile: '2z',
    melds: [],
    options: {
      yaku: yaku(['riichi', 'menzen-tsumo', 'pinfu', 'tanyao', 'iipeiko', 'yakuhai-haku']),
      han: han([2, 3, 4, 5]),
      fu: fuChoices,
      payment: [
        { key: 'dealer-tsumo-700', label: '700点オール' },
        { key: 'dealer-tsumo-1300', label: '1300点オール' },
        { key: 'dealer-tsumo-2000', label: '2000点オール' },
        { key: 'dealer-tsumo-2600', label: '2600点オール' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['menzen-tsumo', 'pinfu'],
        hanKey: '3',
        hanLabel: '3翻',
        fuKey: '20',
        fuLabel: '20符',
        paymentKey: 'dealer-tsumo-1300',
        paymentLabel: '1300点オール',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['menzen-tsumo', 'pinfu'],
      hanKey: '3',
      hanLabel: '3翻',
      fuKey: '20',
      fuLabel: '20符',
      paymentKey: 'dealer-tsumo-1300',
      paymentLabel: '1300点オール',
    },
    fuRequired: true,
    yaku: [
      { label: '門前清自摸和', value: '1翻' },
      { label: '平和', value: '1翻' },
      { label: 'ドラ', value: '1翻', note: 'ドラ表示牌三筒なので四筒がドラ' },
    ],
    fu: [
      { label: '副底', value: '20符' },
      { label: '平和ツモ', value: '0符', note: 'ツモ符を付けない' },
    ],
    explanation:
      '平和ツモは例外的にツモ符を付けず20符です。3翻20符の親ツモは1300点オールです。',
    guideAnchors: ['pinfu', 'table'],
  },
  {
    id: 'q-chiitoi-ron-25-4-child',
    title: '七対子は25符固定',
    difficulty: 'standard',
    prompt: '子のロン和了。七対子の役・符と支払いを選んでください。',
    context: {
      seatWind: '西',
      roundWind: '東',
      dealer: false,
      method: 'ron',
      riichi: '立直',
      conditions: ['門前', 'ロン和了'],
      doraIndicators: ['2s'],
      ruleNotes: ['Mリーグ準拠', '0本場・供託なし'],
    },
    hand: ['1m', '1m', '4m', '4m', '7m', '7m', '2p', '2p', '8p', '8p', '3s', '3s', '6z'],
    winningTile: '6z',
    melds: [],
    options: {
      yaku: yaku(['riichi', 'chiitoitsu', 'toitoi', 'pinfu', 'tanyao', 'iipeiko']),
      han: han([2, 3, 4, 5]),
      fu: fuChoices,
      payment: [
        { key: 'child-ron-3200', label: '3200点' },
        { key: 'child-ron-4800', label: '4800点' },
        { key: 'child-ron-6400', label: '6400点' },
        { key: 'child-ron-8000', label: '8000点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['riichi', 'chiitoitsu'],
        hanKey: '4',
        hanLabel: '4翻',
        fuKey: '25',
        fuLabel: '25符',
        paymentKey: 'child-ron-6400',
        paymentLabel: '6400点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['riichi', 'chiitoitsu'],
      hanKey: '4',
      hanLabel: '4翻',
      fuKey: '25',
      fuLabel: '25符',
      paymentKey: 'child-ron-6400',
      paymentLabel: '6400点',
    },
    fuRequired: true,
    yaku: [
      { label: '立直', value: '1翻' },
      { label: '七対子', value: '2翻' },
      { label: 'ドラ', value: '1翻', note: 'ドラ表示牌二索なので三索がドラ' },
    ],
    fu: [{ label: '七対子', value: '25符固定' }],
    explanation:
      '七対子は通常の副底や待ち符を積まず25符固定です。4翻25符の子ロンは6400点です。',
    guideAnchors: ['chiitoi', 'table'],
  },
  {
    id: 'q-yakuhai-open-40-2-dealer',
    title: '役牌副露と暗刻の40符',
    difficulty: 'standard',
    prompt: '親のロン和了。開いた役牌・翻・符に注意してください。',
    context: {
      seatWind: '東',
      roundWind: '東',
      dealer: true,
      method: 'ron',
      conditions: ['副露あり', 'ロン和了'],
      doraIndicators: ['8s'],
      ruleNotes: ['Mリーグ準拠', '0本場・供託なし'],
    },
    hand: ['1m', '1m', '1m', '2p', '3p', '4p', '7s', '8s', '9s', '5s'],
    winningTile: '5s',
    melds: [
      {
        kind: 'pon',
        tiles: ['7z', '7z', '7z'],
        open: true,
        label: '中ポン',
      },
    ],
    options: {
      yaku: yaku(['yakuhai-chun', 'yakuhai-haku', 'yakuhai-hatsu', 'toitoi', 'sananko', 'honitsu']),
      han: han([1, 2, 3, 4]),
      fu: fuChoices,
      payment: [
        { key: 'dealer-ron-2900', label: '2900点' },
        { key: 'dealer-ron-3900', label: '3900点' },
        { key: 'dealer-ron-5800', label: '5800点' },
        { key: 'dealer-ron-7700', label: '7700点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['yakuhai-chun'],
        hanKey: '2',
        hanLabel: '2翻',
        fuKey: '40',
        fuLabel: '40符',
        paymentKey: 'dealer-ron-3900',
        paymentLabel: '3900点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['yakuhai-chun'],
      hanKey: '2',
      hanLabel: '2翻',
      fuKey: '40',
      fuLabel: '40符',
      paymentKey: 'dealer-ron-3900',
      paymentLabel: '3900点',
    },
    fuRequired: true,
    yaku: [
      { label: '中', value: '1翻' },
      { label: 'ドラ', value: '1翻', note: 'ドラ表示牌八索なので九索がドラ' },
    ],
    fu: [
      { label: '副底', value: '20符' },
      { label: '中の明刻', value: '4符' },
      { label: '一萬の暗刻', value: '8符' },
      { label: '単騎待ち', value: '2符' },
      { label: '切り上げ', value: '40符' },
    ],
    explanation:
      '役牌の明刻は4符、么九牌の暗刻は8符、単騎待ち2符で34符。10符単位へ切り上げて40符です。',
    guideAnchors: ['fu', 'yakuhai'],
  },
  {
    id: 'q-kiriage-60-3-child',
    title: '60符3翻は切り上げ満貫',
    difficulty: 'advanced',
    prompt: '子のロン和了。成立役とMリーグ準拠の切り上げ満貫に注意してください。',
    context: {
      seatWind: '西',
      roundWind: '南',
      dealer: false,
      method: 'ron',
      riichi: '立直',
      conditions: ['門前', 'ロン和了'],
      doraIndicators: ['4p'],
      ruleNotes: ['Mリーグ準拠', '30符4翻と60符3翻は切り上げ満貫'],
    },
    hand: ['9m', '9m', '9m', '1p', '1p', '1p', '2s', '3s', '4s', '4z', '4z', '4z', '7p'],
    winningTile: '7p',
    melds: [],
    options: {
      yaku: yaku(['riichi', 'sananko', 'toitoi', 'yakuhai-hatsu', 'chanta', 'honitsu']),
      han: han([2, 3, 4, 5]),
      fu: fuChoices,
      payment: [
        { key: 'child-ron-7700', label: '7700点' },
        { key: 'child-ron-8000', label: '8000点' },
        { key: 'child-ron-12000', label: '12000点' },
        { key: 'child-ron-16000', label: '16000点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['riichi', 'sananko'],
        hanKey: '3',
        hanLabel: '3翻',
        fuKey: 'not-needed',
        fuLabel: '点数計算上は不要',
        paymentKey: 'child-ron-8000',
        paymentLabel: '8000点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['riichi', 'sananko'],
      hanKey: '3',
      hanLabel: '3翻',
      fuKey: 'not-needed',
      fuLabel: '点数計算上は不要',
      paymentKey: 'child-ron-8000',
      paymentLabel: '8000点',
    },
    fuRequired: false,
    yaku: [
      { label: '立直', value: '1翻' },
      { label: '三暗刻', value: '2翻' },
    ],
    fu: [
      { label: '参考符', value: '60符', note: '暗刻・単騎を含む高符形' },
      { label: '切り上げ満貫', value: '8000点', note: 'Mリーグ準拠' },
    ],
    explanation:
      '60符3翻は通常なら7700点ですが、Mリーグ準拠では切り上げ満貫として8000点です。満貫以上なので回答では符を要求しません。',
    guideAnchors: ['limit', 'table'],
  },
  {
    id: 'q-mangan-child-tsumo',
    title: '子の満貫ツモ',
    difficulty: 'standard',
    prompt: '子のツモ和了。成立役と満貫の支払い形を素早く選びます。',
    context: {
      seatWind: '西',
      roundWind: '東',
      dealer: false,
      method: 'tsumo',
      riichi: '立直',
      conditions: ['門前', 'ツモ和了', '一発'],
      doraIndicators: ['3p'],
      ruleNotes: ['Mリーグ準拠', '0本場・供託なし'],
    },
    hand: ['2m', '3m', '4m', '3p', '4p', '5p', '6p', '7p', '8p', '4s', '5s', '2z', '2z'],
    winningTile: '6s',
    melds: [],
    options: {
      yaku: yaku(['riichi', 'ippatsu', 'menzen-tsumo', 'pinfu', 'tanyao', 'iipeiko']),
      han: han([4, 5, 6, 7]),
      fu: fuChoices,
      payment: [
        { key: 'child-tsumo-1000-2000', label: '1000 / 2000点' },
        { key: 'child-tsumo-2000-4000', label: '2000 / 4000点' },
        { key: 'child-tsumo-3000-6000', label: '3000 / 6000点' },
        { key: 'child-tsumo-4000-8000', label: '4000 / 8000点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['riichi', 'ippatsu', 'menzen-tsumo', 'pinfu'],
        hanKey: '5',
        hanLabel: '5翻',
        fuKey: 'not-needed',
        fuLabel: '点数計算上は不要',
        paymentKey: 'child-tsumo-2000-4000',
        paymentLabel: '2000 / 4000点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['riichi', 'ippatsu', 'menzen-tsumo', 'pinfu'],
      hanKey: '5',
      hanLabel: '5翻',
      fuKey: 'not-needed',
      fuLabel: '点数計算上は不要',
      paymentKey: 'child-tsumo-2000-4000',
      paymentLabel: '2000 / 4000点',
    },
    fuRequired: false,
    yaku: [
      { label: '立直', value: '1翻' },
      { label: '一発', value: '1翻' },
      { label: '門前清自摸和', value: '1翻' },
      { label: '平和', value: '1翻' },
      { label: 'ドラ', value: '1翻', note: 'ドラ表示牌三筒なので四筒がドラ' },
    ],
    fu: [{ label: '参考符', value: '20符', note: '平和ツモ' }],
    explanation:
      '5翻は満貫です。子の満貫ツモは子から2000点、親から4000点を受け取ります。',
    guideAnchors: ['limit', 'payment'],
  },
  {
    id: 'q-honitsu-open-40-3-child',
    title: '喰い下がりの混一色',
    difficulty: 'advanced',
    prompt: '子のロン和了。副露した混一色と役牌を選んでください。',
    context: {
      seatWind: '西',
      roundWind: '南',
      dealer: false,
      method: 'ron',
      conditions: ['副露あり', 'ロン和了'],
      doraIndicators: ['4z'],
      ruleNotes: ['Mリーグ準拠', '0本場・供託なし'],
    },
    hand: ['1p', '2p', '3p', '7p', '8p', '9p', '5z', '5z', '6z', '6z'],
    winningTile: '6z',
    melds: [
      {
        kind: 'chi',
        tiles: ['4p', '5p', '6p'],
        open: true,
        label: '四五六筒チー',
      },
    ],
    options: {
      yaku: yaku(['honitsu', 'yakuhai-hatsu', 'yakuhai-haku', 'yakuhai-chun', 'chanta', 'sanshoku']),
      han: han([2, 3, 4, 5]),
      fu: fuChoices,
      payment: [
        { key: 'child-ron-3900', label: '3900点' },
        { key: 'child-ron-5200', label: '5200点' },
        { key: 'child-ron-7700', label: '7700点' },
        { key: 'child-ron-8000', label: '8000点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['honitsu', 'yakuhai-hatsu'],
        hanKey: '3',
        hanLabel: '3翻',
        fuKey: '30',
        fuLabel: '30符',
        paymentKey: 'child-ron-3900',
        paymentLabel: '3900点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['honitsu', 'yakuhai-hatsu'],
      hanKey: '3',
      hanLabel: '3翻',
      fuKey: '30',
      fuLabel: '30符',
      paymentKey: 'child-ron-3900',
      paymentLabel: '3900点',
    },
    fuRequired: true,
    yaku: [
      { label: '混一色', value: '2翻', note: '副露により3翻から2翻へ喰い下がり' },
      { label: '發', value: '1翻' },
    ],
    fu: [
      { label: '副底', value: '20符' },
      { label: '白の対子', value: '2符' },
      { label: '發の明刻扱い', value: '4符', note: 'ロンで完成した刻子' },
      { label: '切り上げ', value: '30符' },
    ],
    explanation:
      '副露した混一色は2翻です。發1翻と合わせて3翻。白は雀頭の2符にはなりますが、成立役は發です。符は切り上げて30符、子ロンは3900点です。',
    guideAnchors: ['kuisagari', 'fu', 'table'],
  },
  {
    id: 'q-kokushi-child-ron',
    title: '国士無双は役満',
    difficulty: 'limit',
    prompt: '子のロン和了。成立役と役満の支払いを選んでください。',
    context: {
      seatWind: '北',
      roundWind: '東',
      dealer: false,
      method: 'ron',
      conditions: ['門前', 'ロン和了'],
      doraIndicators: ['7p'],
      ruleNotes: ['Mリーグ準拠', '個別のダブル役満なし'],
    },
    hand: ['1m', '9m', '1p', '9p', '1s', '9s', '1z', '2z', '3z', '4z', '5z', '6z', '7z'],
    winningTile: '1m',
    melds: [],
    options: {
      yaku: yaku(['kokushi', 'chiitoitsu', 'honitsu', 'toitoi', 'yakuhai-haku', 'chanta']),
      han: [
        { key: '13', label: '13翻' },
        { key: 'yakuman-1', label: '役満1倍' },
        { key: 'yakuman-2', label: '役満2倍' },
        { key: 'sanbaiman', label: '三倍満' },
      ],
      fu: fuChoices,
      payment: [
        { key: 'child-ron-24000', label: '24000点' },
        { key: 'child-ron-32000', label: '32000点' },
        { key: 'child-ron-48000', label: '48000点' },
        { key: 'child-ron-64000', label: '64000点' },
      ],
    },
    acceptedInterpretations: [
      {
        yakuKeys: ['kokushi'],
        hanKey: 'yakuman-1',
        hanLabel: '役満1倍',
        fuKey: 'not-needed',
        fuLabel: '符計算なし',
        paymentKey: 'child-ron-32000',
        paymentLabel: '32000点',
      },
    ],
    canonicalInterpretation: {
      yakuKeys: ['kokushi'],
      hanKey: 'yakuman-1',
      hanLabel: '役満1倍',
      fuKey: 'not-needed',
      fuLabel: '符計算なし',
      paymentKey: 'child-ron-32000',
      paymentLabel: '32000点',
    },
    fuRequired: false,
    yaku: [{ label: '国士無双', value: '役満1倍' }],
    fu: [{ label: '役満', value: '符計算なし' }],
    explanation:
      'Mリーグ準拠では国士無双十三面待ちの個別ダブル役満はありません。役満1倍の子ロンは32000点です。',
    guideAnchors: ['yakuman'],
  },
]

export function nextQuestionIndex(current: number, answeredCount: number): number {
  void answeredCount
  return (current + 1) % practiceQuestions.length
}

export function getQuestionById(id: string): PracticeQuestion | undefined {
  return practiceQuestions.find((question) => question.id === id)
}
